import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/ui/shared/theme-provider"
import { Toaster } from "@/components/ui/shared/sonner"
import { SidebarProvider } from "@/components/ui/shared/sidebar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <SidebarProvider>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <div className="w-11/12 h-screen m-auto p-10">
                            {children}
                            <Toaster />
                        </div>
                    </ThemeProvider>
                </SidebarProvider>
            </body>
        </html>
    )
}
